version: "3.8"
services:
  vprodb:
    image: ayoolacoul27/bro-db:1.0
    ports: 
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    image: ayoolacoul27/bro-app:1.0
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
   
  vproweb:
    image: ayoolacoul27/bro-web:1.0
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
